import { useGSAP } from '@gsap/react';
import gsap from 'gsap';
import React, { useRef } from 'react'

function Stats() {

    return (
        <div>
            <div className='stagger'>
                <span className='font-bold'>10,000+</span> farmers empowered through training & mentorship.
            </div>
            <div className='stagger'>
                <span className='font-bold'>₹28L+</span> extra income generated by connecting farmers to fair markets.
            </div>
            <div className='stagger'>
                <span className='font-bold'>24</span> villages reached across 3 states.
            </div>
            <div className='stagger'>
                <span className='font-bold'>12%</span> reduction in water usage with better irrigation practices.
            </div>
            <div className='stagger'>
                <span className='font-bold'>340</span> women farmers empowered with leadership and farm management skills.
            </div>
            <div className='stagger'>
                <span className='font-bold'>2,300</span> trees planted as part of agroforestry drives.
            </div>
            <div className='stagger'>
                <span className='font-bold'>22%</span> decrease in chemical pesticide use through natural alternatives.
            </div>
        </div>
    )
}

export default Stats