const mentors = [
    {
        name: "Dr. Meera Singh",
        profilePic: "https://images.pexels.com/photos/33790726/pexels-photo-33790726.jpeg", // Portrait of Weathered Senior Farmer :contentReference[oaicite:0]{index=0}
        designation: "Senior Agronomist",
        guided: 47,
        expertise: "Organic Soil & Crop Rotation",
        experience: "15 years",
        location: "Maharashtra, India",
        organization: "AgriLife Foundation",
        bio: "Dedicated to improving soil health and teaching sustainable farming practices in rural communities.",
        contribution: "Introduced composting programs across 20 villages, improving soil fertility and yield.",
        specialPrograms: ["Soil Health Workshops", "Organic Certification Support"]
    },
    {
        name: "Rajesh Kumar",
        profilePic: "https://images.pexels.com/photos/12833203/pexels-photo-12833203.jpeg", // Portrait of Farmer :contentReference[oaicite:1]{index=1}
        designation: "Water Conservation Specialist",
        guided: 35,
        expertise: "Irrigation Techniques & Water Management",
        experience: "12 years",
        location: "Karnataka, India",
        organization: "BlueDrop NGO",
        bio: "Works on implementing efficient water use systems and promoting drip irrigation among smallholder farmers.",
        contribution: "Established rainwater harvesting units in 15 villages; reduced water usage by 30%.",
        specialPrograms: ["Rainwater Harvesting", "Drip Irrigation Training"]
    },
    {
        name: "Anjali Rao",
        profilePic: "https://images.pexels.com/photos/14932307/pexels-photo-14932307.jpeg", // Portrait of Farmer :contentReference[oaicite:2]{index=2}
        designation: "Women Empowerment Lead",
        guided: 52,
        expertise: "Leadership & Farm Management for Women",
        experience: "10 years",
        location: "Uttar Pradesh, India",
        organization: "Harvest Hands",
        bio: "Leads programs that help women farmers gain skills in farm planning, marketing, and leadership.",
        contribution: "Trained over 50 women in sustainable farm management; helped form two cooperatives.",
        specialPrograms: ["Women’s Leadership Program", "Market Linkage Schemes"]
    },
    {
        name: "Mohammad Faiz",
        profilePic: "https://images.pexels.com/photos/13513473/pexels-photo-13513473.jpeg",
        designation: "Pest Management Specialist",
        guided: 29,
        expertise: "Integrated Pest Control & Crop Health",
        experience: "8 years",
        location: "Punjab, India",
        organization: "GreenFields Initiative",
        bio: "Helps farmers reduce chemical usage by teaching natural pest control techniques and disease prevention.",
        contribution: "Decreased pesticide cost by 40% for groups he worked with; improved crop health significantly.",
        specialPrograms: ["Biopesticide Training", "Crop Disease Monitoring"]
    },
    {
        name: "Leela Das",
        profilePic: "https://images.pexels.com/photos/13513471/pexels-photo-13513471.jpeg",
        designation: "Market Access & Fair Trade Expert",
        guided: 41,
        expertise: "Supply Chain & Cooperative Development",
        experience: "11 years",
        location: "West Bengal, India",
        organization: "FarmersConnect",
        bio: "Builds connections between small farmers and fair markets, ensuring better pricing.",
        contribution: "Helped set up 5 cooperatives; opened new market channels for over 200 farmers.",
        specialPrograms: ["Cooperative Training", "Fair Trade Certification"]
    },
    {
        name: "Suresh Patil",
        profilePic: "https://images.pexels.com/photos/13513474/pexels-photo-13513474.jpeg",
        designation: "Crop Technologies Advisor",
        guided: 38,
        expertise: "High Yield Variety Introduction & Crop Rotation",
        experience: "9 years",
        location: "Madhya Pradesh, India",
        organization: "SeedGrowth Org",
        bio: "Introduces improved seed varieties and teaches crop rotation to prevent soil depletion.",
        contribution: "Implemented two high-yield varietals in 10 districts; increased yields by about 25%.",
        specialPrograms: ["Seed Demonstration Plots", "Rotation Workshops"]
    },
    {
        name: "Vandana Iyer",
        profilePic: "https://images.pexels.com/photos/13513475/pexels-photo-13513475.jpeg",
        designation: "Sustainable Farming Mentor",
        guided: 44,
        expertise: "Agroforestry & Soil Conservation",
        experience: "13 years",
        location: "Kerala, India",
        organization: "EarthRoots",
        bio: "Promotes agroforestry and preventing erosion through terracing and tree planting.",
        contribution: "Planted over 10,000 trees in farm perimeters; reduced topsoil loss significantly.",
        specialPrograms: ["Tree Planting Drives", "Soil Conservation Camps"]
    },
    {
        name: "Harish Nair",
        profilePic: "https://images.pexels.com/photos/13513476/pexels-photo-13513476.jpeg",
        designation: "Harvest & Post-Harvest Specialist",
        guided: 31,
        expertise: "Storage Technology & Loss Reduction",
        experience: "7 years",
        location: "Tamil Nadu, India",
        organization: "HarvestSafe",
        bio: "Teaches best practices for storage, reducing post-harvest losses and increasing incomes.",
        contribution: "Implemented storage units in 8 villages; reduced waste by ~30%.",
        specialPrograms: ["Storage Facility Workshops", "Cold Chain Training"]
    },
    {
        name: "Priya Menon",
        profilePic: "https://images.pexels.com/photos/13513477/pexels-photo-13513477.jpeg",
        designation: "Certification & Organic Specialist",
        guided: 46,
        expertise: "Organic Certification & Quality Control",
        experience: "12 years",
        location: "Kerala, India",
        organization: "PureFarm Org",
        bio: "Supports farmers to get organic certification and maintain quality standards.",
        contribution: "Guided 120 farmers to achieve organic certification; improved market price premium.",
        specialPrograms: ["Quality Audits", "Organic Standards Workshops"]
    },
    {
        name: "Ravi Pillai",
        profilePic: "https://images.pexels.com/photos/13513478/pexels-photo-13513478.jpeg",
        designation: "Livestock & Dairy Expert",
        guided: 33,
        expertise: "Animal Husbandry & Dairy Farming",
        experience: "10 years",
        location: "Maharashtra, India",
        organization: "DairyPlus NGO",
        bio: "Works with farmers on improving livestock health and boosting dairy productivity.",
        contribution: "Introduced better feed and vaccination programs in several villages; increased milk yield by ~20%.",
        specialPrograms: ["Dairy Health Camps", "Feed Improvement"]
    },
    // {
    //     name: "Geeta Sharma",
    //     profilePic: "https://images.pexels.com/photos/13513479/pexels-photo-13513479.jpeg",
    //     designation: "Agroforestry Specialist",
    //     guided: 39,
    //     expertise: "Tree Crop Systems & Agroforestry",
    //     experience: "14 years",
    //     location: "Himachal Pradesh, India",
    //     organization: "GreenCanopy",
    //     bio: "Designs agroforestry systems to diversify income and protect soil and water.",
    //     contribution: "Helped integrate fruit trees into 30 farms; improved biodiversity and shade cover.",
    //     specialPrograms: ["Tree Crop Training", "Forest-Farm Integration"]
    // },
    // {
    //     name: "Abdul Rahman",
    //     profilePic: "https://images.pexels.com/photos/13513480/pexels-photo-13513480.jpeg",
    //     designation: "Farm Finance Advisor",
    //     guided: 28,
    //     expertise: "Farm Budgeting & Access to Credit",
    //     experience: "11 years",
    //     location: "Rajasthan, India",
    //     organization: "FinAgri Support",
    //     bio: "Helps farmers plan finances, access micro-credit and manage loans responsibly.",
    //     contribution: "Helped 70 farmers obtain low-interest credit; improved repayment rates.",
    //     specialPrograms: ["Financial Literacy Sessions", "Micro-Credit Partnerships"]
    // },
    // {
    //     name: "Latha Reddy",
    //     profilePic: "https://images.pexels.com/photos/13513481/pexels-photo-13513481.jpeg",
    //     designation: "Post-Harvest & Value Addition Expert",
    //     guided: 42,
    //     expertise: "Value Addition & Processing",
    //     experience: "9 years",
    //     location: "Andhra Pradesh, India",
    //     organization: "HarvestPlus",
    //     bio: "Teaches farmers how to process and add value to crops, increasing profit margins.",
    //     contribution: "Set up small processing units for 20 communities; raised incomes by 30%.",
    //     specialPrograms: ["Food Processing Workshops", "Packaging Design"]
    // },
    // {
    //     name: "Sakshi Gupta",
    //     profilePic: "https://images.pexels.com/photos/13513482/pexels-photo-13513482.jpeg",
    //     designation: "Technology in Agriculture Lead",
    //     guided: 34,
    //     expertise: "Smart Farming & Precision Tools",
    //     experience: "8 years",
    //     location: "Telangana, India",
    //     organization: "AgriTech Hub",
    //     bio: "Introduces tech tools like soil sensors, mobile apps, and weather forecasting to farmers.",
    //     contribution: "Deployed 50 sensor kits; improved decision-making and resource efficiency.",
    //     specialPrograms: ["Sensor Deployment", "Mobile Weather Alerts"]
    // },
    // {
    //     name: "Manoj Varma",
    //     profilePic: "https://images.pexels.com/photos/13513483/pexels-photo-13513483.jpeg",
    //     designation: "Crop Diversification Specialist",
    //     guided: 30,
    //     expertise: "Mixed Cropping & Diversification",
    //     experience: "10 years",
    //     location: "Odisha, India",
    //     organization: "DiversiFarm",
    //     bio: "Helps farmers reduce risk by growing multiple crop types and rotating them sensibly.",
    //     contribution: "Introduced mixed cropping in 25 villages; increased resilience to climate variability.",
    //     specialPrograms: ["Diversification Training", "Crop Blend Experiments"]
    // },
    // {
    //     name: "Neha Desai",
    //     profilePic: "https://images.pexels.com/photos/13513484/pexels-photo-13513484.jpeg",
    //     designation: "Nutrition & Crop Quality Specialist",
    //     guided: 36,
    //     expertise: "Nutrient Management & Crop Quality",
    //     experience: "7 years",
    //     location: "Gujarat, India",
    //     organization: "NutriHarvest",
    //     bio: "Works with farmers to optimize soil nutrients and improve quality of fruits & vegetables.",
    //     contribution: "Reduced fertilizer waste; improved nutritional content of produce.",
    //     specialPrograms: ["Soil Testing Camps", "Quality Control Workshops"]
    // },
    // {
    //     name: "Vikas Singh",
    //     profilePic: "https://images.pexels.com/photos/13513485/pexels-photo-13513485.jpeg",
    //     designation: "Climate Adaptation Advisor",
    //     guided: 32,
    //     expertise: "Adaptive Agriculture & Resilience Planning",
    //     experience: "10 years",
    //     location: "Uttarakhand, India",
    //     organization: "ClimateFarm Advocates",
    //     bio: "Helps farmers adjust to changing weather patterns, droughts, and uncertain rainfall.",
    //     contribution: "Developed adaptation plans for 15 districts; saved crops during early droughts.",
    //     specialPrograms: ["Resilience Workshops", "Adaptive Crop Calendars"]
    // }
];
export default mentors;